# Generated by Selenium IDE
import pytest
import numpy
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from base.web_ui.demoProject.web_ui_demoProject_client import WEB_UI_DemoProject_Client
import time
class TestDemo2():
  def setup_method(self, method):
    #self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.driver = webdriver.Firefox()
    self.vars = {}
    #self.demoProjectClient = WEB_UI_DemoProject_Client()
    #self.indexPage = IndexPage(self.demoProjectClient.browserOperator)
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_demo2(self):
    # Test name: demo2
    # Step # | name | target | value
    # 1 | open | /passports/login?service=https%3A%2F%2Ftjsh.ushayden.com%2Fportals%2Fcas&tenantCode=tjsh&trial=false |
    #self.demoProjectClient.
    self.driver.get("https://tjsh.ushayden.com/passports/login?service=https%3A%2F%2Ftjsh.ushayden.com%2Fportals%2Fcas&tenantCode=tjsh&trial=false")
    # 2 | setWindowSize | 1550x840 | 
    self.driver.set_window_size(1550, 840)
    # 3 | click | id=pwd1 |
    self.driver.find_element(By.ID, "name").click()
    # 4 | type | id=pwd1 | 123456
    self.driver.find_element(By.ID, "name").send_keys("liyh490")
    #self.driver.get_screenshot_as_file()
    assert 7 == numpy.add(3, 4), "方法返回的值不等于6，而是等于{0}".format(numpy.add(3, 4))
    # 3 | click | id=pwd1 | 
    self.driver.find_element(By.ID, "pwd1").click()
    # 4 | type | id=pwd1 | 123456
    self.driver.find_element(By.ID, "pwd1").send_keys("123456")
    # 5 | click | linkText=登录 | 
    self.driver.find_element(By.XPATH, '/html/body/form/div[2]/a').click()
    #Locator_Type.XPATH, '/html/body/form/div[2]/a'
    # 6 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 7 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 8 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 10 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(10)
    # 11 | click | css=.sl-navitem:nth-child(1) .title | 
    self.driver.find_element(By.CSS_SELECTOR, ".sl-navitem:nth-child(1) .title").click()
    # 12 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 13 | click | css=.children .sl-navitem:nth-child(1) .title |
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(1) .title").click()
    # 14 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 15 | click | css=.children .sl-navitem:nth-child(2) .title |
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(2) .title").click()
    # 16 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 17 | click | css=.children .sl-navitem:nth-child(3) .title |
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(3) .title").click()
    time.sleep(10)
    # 18 | click | css=.children .sl-navitem:nth-child(4) .title | 
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(4) .title").click()
    time.sleep(10)
    # 19 | click | css=.children .sl-navitem:nth-child(5) .title | 
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(5) .title").click()
    # 20 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 21 | click | css=.children .sl-navitem:nth-child(6) .title |
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(6) .title").click()
    time.sleep(10)
    # 22 | click | css=.children .sl-navitem:nth-child(7) .title | 
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(7) .title").click()
    # 23 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 24 | click | css=.children .sl-navitem:nth-child(8) .title |
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(8) .title").click()
    # 25 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 26 | click | css=.children .sl-navitem:nth-child(9) .title |
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(9) .title").click()
    # 27 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 28 | click | css=.children .sl-navitem:nth-child(10) .title |
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(10) .title").click()
    # 29 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
  
# if __name__ == '__main__':
#     pytest.main(['-v','--html=report01.html','1test_demo2_all.py'])