# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDemo1():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_demo1(self):
        # Test name: demo1
        # Step # | name | target | value
        # 1 | open | /passports/login?service=https%3A%2F%2Ftjsh.ushayden.com%2Fportals%2Fcas&tenantCode=tjsh&trial=false |
        self.driver.get(
            "https://tjsh.ushayden.com/passports/login?service=https%3A%2F%2Ftjsh.ushayden.com%2Fportals%2Fcas&tenantCode=tjsh&trial=false")
        # 2 | setWindowSize | 1550x840 |
        self.driver.set_window_size(1550, 840)
        # 3 | click | id=pwd1 |
        self.driver.find_element(By.ID, "pwd1").click()
        # 4 | type | id=pwd1 | 123456
        self.driver.find_element(By.ID, "pwd1").send_keys("123456")
        # 5 | click | linkText=登录 |
        self.driver.find_element(By.LINK_TEXT, "登录").click()

        # 6 | runScript | window.scrollTo(0,0) |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 7 | runScript | window.scrollTo(0,0) |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 8 | runScript | window.scrollTo(0,0) |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 9 | click | css=.sl-navitem:nth-child(1) .title |
        self.driver.find_element(By.CSS_SELECTOR, ".sl-navitem:nth-child(1) .title").click()
        # 10 | runScript | window.scrollTo(0,0) |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 11 | click | css=.children .sl-navitem:nth-child(1) .title |
        self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(1) .title").click()
        # 12 | runScript | window.scrollTo(0,0) |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 13 | runScript | window.scrollTo(0,0) |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 14 | click | linkText=关闭 |
        self.driver.find_element(By.LINK_TEXT, "关闭").click()
        # 15 | click | css=.selected > .check > .value |
        self.driver.find_element(By.CSS_SELECTOR, ".selected > .check > .value").click()
        # 16 | runScript | window.scrollTo(0,0) |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 17 | click | linkText=查看 |
        self.driver.find_element(By.LINK_TEXT, "查看").click()
        # 18 | runScript | window.scrollTo(0,0) |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 19 | click | linkText=返回 |
        self.driver.find_element(By.LINK_TEXT, "返回").click()
        # 20 | click | css=.textinput:nth-child(5) div > div |
        self.driver.find_element(By.CSS_SELECTOR, ".textinput:nth-child(5) div > div").click()
        # 21 | runScript | window.scrollTo(0,0) |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 22 | type | css=.fixed input | 电
        self.driver.find_element(By.CSS_SELECTOR, ".fixed input").send_keys("电")
        # 23 | click | linkText=查询 |
        self.driver.find_element(By.LINK_TEXT, "查询").click()
        # 24 | click | css=.user-name |
        self.driver.find_element(By.CSS_SELECTOR, ".user-name").click()
        # 25 | runScript | window.scrollTo(0,0) |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 26 | click | css=.icon-headermenu-logout |
        self.driver.find_element(By.CSS_SELECTOR, ".icon-headermenu-logout").click()

