# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestZuoyedengjibiao():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.driver.implicitly_wait(30)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_zuoyedengjibiao(self):
    # Test name: zuoyedengjibiao
    # Step # | name | target | value
    # 1 | open | /passports/login?service=https%3A%2F%2Ftjsh.ushayden.com%2Fportals%2Fcas&tenantCode=tjsh&trial=false | 
    self.driver.get("https://tjsh.ushayden.com/passports/login?service=https%3A%2F%2Ftjsh.ushayden.com%2Fportals%2Fcas&tenantCode=tjsh&trial=false")
    # 2 | setWindowSize | 940x765 | 
    self.driver.set_window_size(940, 765)
    # 3 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 4 | type | id=name | zhai
    self.driver.find_element(By.ID, "name").send_keys("zhai")
    # 5 | type | id=pwd1 | 123456
    self.driver.find_element(By.ID, "pwd1").send_keys("123456")
    # 6 | click | linkText=登录 | 
    #.driver.find_element(By.LINK_TEXT, "登录").click()
    self.driver.find_element(By.XPATH, '/html/body/form/div[2]/a').click()
    time.sleep(10)
    # 7 | mouseOver | css=.logo > div | 
    # element = self.driver.find_element(By.CSS_SELECTOR, ".logo > div")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # 8 | click | css=.sl-navitem:nth-child(1) .title | 
    self.driver.find_element(By.CSS_SELECTOR, ".sl-navitem:nth-child(1) .title").click()
    time.sleep(3)
    # 9 | click | css=.children .sl-navitem:nth-child(7) .title | 
    self.driver.find_element(By.CSS_SELECTOR, ".children .sl-navitem:nth-child(7) .title").click()
    # time.sleep(3)
    # # 10 | click | css=.dateinput:nth-child(3) div > div |
    # self.driver.find_element(By.CSS_SELECTOR, ".dateinput:nth-child(3) div > div").click()
    # time.sleep(3)
    # # 11 | click | css=tr:nth-child(2) > td:nth-child(1) > .date |
    # self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(1) > .date").click()
    # time.sleep(3)
    # # 12 | click | css=.dateinput:nth-child(4) div > div |
    # self.driver.find_element(By.CSS_SELECTOR, ".dateinput:nth-child(4) div > div").click()
    # time.sleep(3)
    # # 13 | click | linkText=今 天 |
    # self.driver.find_element(By.LINK_TEXT, "今 天").click()
    # # 14 | click | linkText=查询 |
    # self.driver.find_element(By.LINK_TEXT, "查询").click()

if __name__ == '__main__':
    pytest.main(['-v','--html=report03.html','test_zuoyedengjibiao.py'])
