# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMangbanguanli():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.driver.implicitly_wait(30)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mangbanguanli(self):
    # Test name: mangbanguanli
    # Step # | name | target | value
    # 1 | open | /passports/login?service=https%3A%2F%2Ftjsh.ushayden.com%2Fportals%2Fcas&tenantCode=tjsh&trial=false | 
    self.driver.get("https://tjsh.ushayden.com/passports/login?service=https%3A%2F%2Ftjsh.ushayden.com%2Fportals%2Fcas&tenantCode=tjsh&trial=false")
    # 2 | setWindowSize | 940x765 | 
    self.driver.set_window_size(940, 765)
    # 3 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 4 | type | id=name | zhai
    self.driver.find_element(By.ID, "name").send_keys("zhai")
    # 5 | type | id=pwd1 | 123456
    self.driver.find_element(By.ID, "pwd1").send_keys("123456")
    # 6 | click | linkText=登录 | 
    #self.driver.find_element(By.LINK_TEXT, "登录").click()
    self.driver.find_element(By.XPATH, '/html/body/form/div[2]/a').click()
    time.sleep(10)
    # 7 | click | css=.sl-navitem:nth-child(1) .title | 
    self.driver.find_element(By.CSS_SELECTOR, ".sl-navitem:nth-child(1) .title").click()
    time.sleep(3)
    # 8 | click | css=.sl-navitem:nth-child(17) .title | 
    self.driver.find_element(By.CSS_SELECTOR, ".sl-navitem:nth-child(17) .title").click()
    time.sleep(3)
    # # 9 | mouseOver | linkText=删除 |
    # element = self.driver.find_element(By.LINK_TEXT, "删除")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # # 10 | mouseOut | linkText=删除 |
    # element = self.driver.find_element(By.CSS_SELECTOR, "body")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element, 0, 0).perform()
    # 11 | click | linkText=添加 | 
    self.driver.find_element(By.LINK_TEXT, "添加").click()

if __name__ == '__main__':
    pytest.main(['-v','--html=report03.html','test_mangbanguanli.py'])
  
