# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSileizizhitaizhang_jhur():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.driver.implicitly_wait(30)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sileizizhitaizhang(self):
    # Test name: sileizizhitaizhang
    # Step # | name | target | value
    # 1 | open | /passports/login?service=https%3A%2F%2Ftjsh.ushayden.com%2Fportals%2Fcas&tenantCode=tjsh&trial=false | 
    self.driver.get("https://tjsh.ushayden.com/passports/login?service=https%3A%2F%2Ftjsh.ushayden.com%2Fportals%2Fcas&tenantCode=tjsh&trial=false")
    # 2 | setWindowSize | 940x765 | 
    self.driver.set_window_size(940, 765)
    # 3 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 4 | type | id=name | zhai
    self.driver.find_element(By.ID, "name").send_keys("zhai")
    # 5 | type | id=pwd1 | 123456
    self.driver.find_element(By.ID, "pwd1").send_keys("123456")
    # 6 | click | linkText=登录 | 
    #self.driver.find_element(By.LINK_TEXT, "登录").click()
    self.driver.find_element(By.XPATH, '/html/body/form/div[2]/a').click()
    time.sleep(10)
    # 7 | click | css=.sl-navitem:nth-child(1) .title | 
    self.driver.find_element(By.CSS_SELECTOR, ".sl-navitem:nth-child(1) .title").click()
    time.sleep(3)
    # 8 | click | css=.extnavcontent .sl-navitem:nth-child(1) .title | 点击四类资质台账
    self.driver.find_element(By.XPATH, "/html/body/div[1]/div/div[2]/div[1]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[18]/span/span").click()
    time.sleep(3)

    #监护人资质台账
    self.driver.find_element(By.XPATH,
                             "/html/body/div[1]/div/div[2]/div[1]/div/div[3]/div/div/div/div/div/div[2]/div/div/div[1]/div/ul/li[3]/span/span").click()
    time.sleep(10)
    # 14 | click | css=.extnavcontent .sl-navitem:nth-child(3) .title | 
    #self.driver.find_element(By.CSS_SELECTOR, ".extnavcontent .sl-navitem:nth-child(3) .title").click()
    # 15 | click | linkText=添加 | 
    self.driver.find_element(By.LINK_TEXT, "添加").click()
    time.sleep(3)
    # 16 | click | linkText=返回 | 
    self.driver.find_element(By.LINK_TEXT, "返回").click()

  
if __name__ == '__main__':
    pytest.main(['-v','--html=report04.html','test_sileizizhitaizhang_jhur.py'])